basePath: /
host: http://localhost:1324
info:
  contact: {}
  description: KNOV API \n http://localhost:1324
  title: Knov API
  version: "1.0"
paths:
  /api/health:
    get:
      responses: {}
      summary: Health check
  /api/themes:
    get:
      description: Get current theme and available themes, or set new theme via query
        parameter
      parameters:
      - description: Theme name to set (POST only)
        in: query
        name: theme
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"current":"themename","available":["theme1","theme2"]}'
          schema:
            type: string
      summary: Get and set themes
      tags:
      - themes
    post:
      description: Get current theme and available themes, or set new theme via query
        parameter
      parameters:
      - description: Theme name to set (POST only)
        in: query
        name: theme
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"current":"themename","available":["theme1","theme2"]}'
          schema:
            type: string
      summary: Get and set themes
      tags:
      - themes
swagger: "2.0"
